# Generated by Django 3.2.3 on 2021-06-01 20:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Country')),
                ('m_poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Coordinates')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='City')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='cities/', verbose_name='Image')),
                ('m_poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Coordinates')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Capital')),
                ('m_poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Coordinates')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='country.country', verbose_name='Capital')),
            ],
            options={
                'verbose_name': 'Capital',
            },
        ),
    ]
