# Generated by Django 3.2.3 on 2021-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='m_poly',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='m_poly',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='m_poly',
            new_name='location',
        ),
    ]
